OPENDJ-1368 Remove AttributeValue OPENDJ-1379 NoClassDefFoundError while doing REST read operation on the http connection handler
Removed uses of AttributeValue interface replaced by ByteString class.
Removed uses of AttributeValues class.


git-svn-id: https://svn.forgerock.org/opendj/trunk@10557 41b1ffd8-f28e-4786-ab96-9950f0a78031